dailyfresh/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('df_user.urls'), name="user"),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('', include('df_goods.urls')),
    path('detail/', include('df_goods.urls')),
    path('cart/', include('df_cart.urls')),
    path('order/', include('df_order.urls')),
]

if settings.DEBUG:
    media_root = os.path.join(settings.BASE_DIR, settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=media_root)

df_cart/urls.py
#__author: "haichong"
#date: 2018/11/2
from django.urls import re_path
from . import views
urlpatterns = [
    re_path(r'^$', views.cart, name='cart'),
    re_path(r'^add(\d+)_(\d+)/$', views.add),
    re_path(r'^edit(\d+)_(\d+)/$', views.edit),
    re_path(r'^delete(\d+)/$', views.delete),
]

df_user/urls.py
#__author: "haichong"
#date: 2018/10/15
from django.conf.urls import re_path
from . import views

urlpatterns = [
	re_path(r'^register/$', views.register),
	re_path(r'^register_handle/$', views.register_handle),
	re_path(r'^register_exist/$', views.register_exist),
	re_path(r'^login/$', views.login),
	re_path(r'^login_handle/$', views.login_handle),
	re_path(r'^logout/$', views.logout),
	re_path(r'^info/$', views.info),
	re_path(r'^site/$', views.site),
	re_path(r'^order/(\d+)$', views.order),
]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

df_order/models.py
from django.db import models

# Create your models here.
class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True)
    user = models.ForeignKey('df_user.UserInfo', on_delete=models.CASCADE)
    odate = models.DateTimeField(auto_now=True)
    oIsPay = models.BooleanField(default=False)
    ototal = models.DecimalField(max_digits=6, decimal_places=2)
    oaddress = models.CharField(max_length=150)

class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo', on_delete=models.CASCADE)
    order = models.ForeignKey(OrderInfo, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    count = models.IntegerField()

df_user/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
	uname = models.CharField(max_length=20)
	# 加密sha(40) md5(16)
	upwd = models.CharField(max_length=40)
	uemail = models.CharField(max_length=30)
	ushou = models.CharField(max_length=20, default='')
	uaddress = models.CharField(max_length=100, default='')
	uyoubian = models.CharField(max_length=6, default='')
	uphone = models.CharField(max_length=11, default='')

	#default, blank是python层面的约束, 不影响数据库表结构
	def __str__(self):
		return self.uname
	class Meta:
		verbose_name = '用户信息'
		verbose_name_plural = '用户信息'

df_user/views.py
from django.core.paginator import Paginator
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, render_to_response
from .models import *
from df_goods.models import *
from hashlib import sha1
from df_order.models import *
from . import user_decorator


# Create your views here.
def register(request):
    return render(request, 'df_user/register.html', {'title': '用户注册'})


def register_handle(request):
    # 接受用户输入
    post = request.POST
    uname = post.get('user_name')
    upwd = post.get('pwd')
    upwd2 = post.get('cpwd')
    uemail = post.get('email')

    # 判断两次密码
    if upwd != upwd2:
        return redirect('/user/register/')

    # 密码加密
    s1 = sha1()
    s1.update(upwd.encode('utf-8'))
    upwd3 = s1.hexdigest()

    # 创建对象
    user = UserInfo()
    user.uname = uname
    user.upwd = upwd3
    user.uemail = uemail
    user.save()

    request.session['uname'] = uname
    # 注册成功, 转到登录页面
    return redirect('/user/login/')


def register_exist(request):
    uname = request.GET.get('uname')
    count = UserInfo.objects.filter(uname=uname).count()
    return JsonResponse({'count': count})


def login(request):
    uname = request.COOKIES.get('uname', '')
    if not uname:
        uname = request.session.get('uname', '')
    context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 0, 'uname': uname}
    return render(request, 'df_user/login.html', context)


def login_handle(request):
    post = request.POST
    uname = post.get('username')
    upwd = post.get('pwd')
    jizhu = post.get('jizhu', 0)

    users = UserInfo.objects.filter(uname=uname)
    if len(users) == 1:
        s1 = sha1()
        s1.update(upwd.encode('utf-8'))
        if s1.hexdigest() == users[0].upwd:
            red = HttpResponseRedirect('/user/info/')
            if jizhu != 0:
                red.set_cookie('uname', uname)
            else:
                red.set_cookie('uname', '', max_age=-1)
            request.session['user_id'] = users[0].id
            request.session['user_name'] = uname
            return red
        else:
            context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 1, 'uname': uname, 'upwd': upwd}
            return render(request, 'df_user/login.html', context)
    else:
        context = {'title': '用户登录', 'error_name': 1, 'error_pwd': 0, 'uname': uname, 'upwd': upwd}
        return render(request, 'df_user/login.html', context)


def logout(request):
    del request.session['user_id']
    del request.session['user_name']
    return redirect('/')


@user_decorator.login
def info(request):
    user_email = UserInfo.objects.get(id=request.session['user_id']).uemail
    goods_ids = request.session.get(str(request.session['user_id']), '')
    goods_list = []
    if goods_ids != '':
        for goods_id in goods_ids:
            goods_list.append(GoodsInfo.objects.get(id=int(goods_id)))
    context = {
        'title': '天天生鲜-用户中心',
        'user_email': user_email,
        'user_name': request.session['user_name'],
        'goods_list': goods_list
    }
    return render(request, 'df_user/user_center_info.html', context)


@user_decorator.login
def order(request, index):
    user_id = request.session['user_id']
    orders_list = OrderInfo.objects.filter(user_id=int(user_id)).order_by('-odate')
    # print(len(orders_list))
    # print(orders_list)
    paginator = Paginator(orders_list, 2)
    page = paginator.page(int(index))
    context = {
        'paginator': paginator,
        'page': page,
        # 'orders_list':orders_list,
        'title': "用户中心",
        'page_name': 1,
    }
    return render(request, 'df_user/user_center_order.html', context)


@user_decorator.login
def site(request):
    user = UserInfo.objects.get(id=request.session['user_id'])
    if request.method == 'POST':
        post = request.POST
        user.ushou = post.get('ushou')
        user.uaddress = post.get('uaddress')
        user.uyoubian = post.get('uyoubian')
        user.uphone = post.get('uphone')
        user.save()
    context = {
        'title': '天天生鲜-用户中心',
        'user': user
    }
    return render(request, 'df_user/user_center_site.html', context)

templates/df_user/base.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{{ title }}-天天生鲜</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %} ">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    {%block head%}{%endblock head%}
</head>

<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!<a href="/" style="margin-left: 10px;">返回首页</a></div>
			<div class="fr">
                {% if request.session.user_name|default:'' != '' %}
                    <div class="login_btn fl">
                        <a>欢迎您:</a>
                        <a>{{request.session.user_name}}</a>
                        <span>|</span>
                        <a href="/user/logout/">注销</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="/user/login/">登录</a>
                        <span>|</span>
                        <a href="/user/register/">注册</a>
                    </div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/info/">用户中心</a>
					<span>|</span>
					<a href="/cart/">我的购物车</a>
					<span>|</span>
					<a href="/user/order/1">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{ title }}</div>
		<form class="search_con fr" action="/search/" method="get">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
		</form>
	</div>
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
</html>

templates/df_user/base_foot.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    {% block head %}{% endblock head %}
</head>
<body>
{% block body %}{% endblock body %}
<div class="footer no-mp">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>
</body>
</html>

templates/df_user/login.html
{% extends 'df_user/base_foot.html' %}
{% load static %}
{% block head %}
    <script type="text/javascript">
         $(function () {
            name_error=false;
            pwd_error=false;

            if({{error_name}}==1){
                $('.user_error').html('用户名错误').show();
            }
            if({{error_pwd}}==1){
                $('.pwd_error').html('密码错误').show();
            }
            
            $('.name_input').blur(function () {
                if($('.name_input').val().length==0){
                    $('.user_error').html('请填写用户名').show();
                    name_error=false;
                }else{
                    $('.user_error').hide();
                    name_error=true;
                }      
            })
            
            $('.pass_input').blur(function () {
                if($('.pass_input').val().length==0){
                    $('.pwd_error').html('请填写密码').show();
                    pwd_error=false;
                }else{
                    $('.pwd_error').hide();
                    pwd_error=true;
                }      
            })
        })
    </script>
{% endblock head %}
{% block body %}
    <div class="login_top clearfix">
        <a href="index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
    </div>
    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">日夜兼程 · 急速送达</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登录</h1>
                    <a href="/user/register/">立即注册</a>
                </div>
                <div class="form_input">
                    <form method="post" action="/user/login_handle/">
                        {% csrf_token %}
                        <input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{ uname }}">
                        <div class="user_error">输入错误</div>
                        <input type="password" name="pwd" class="pass_input" placeholder="请输入密码" value="{{ upwd }}">
                        <div class="pwd_error">输入错误</div>
                        <div class="more_input clearfix">
                            <input type="checkbox" name="jizhu" checked="checked" value="1">
                            <label>记住用户名</label>
                            <a href="#">忘记密码</a>
                        </div>
                        <input type="submit" name="" value="登录" class="input_submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

templates/df_user/register.html
{% extends 'df_user/base_foot.html' %}
{% load static %}
{% block head %}
    <script type="text/javascript" src="{% static 'df_user/js/register.js' %}"></script>
{% endblock head %}
{% block body %}
    <div class="register_con">
        <div class="l_con fl">
            <a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
            <div class="reg_slogan">足不出户 · 新鲜每一天</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>用户注册</h1>
                <a href="/user/login/">登录</a>
            </div>
            <div class="reg_form clearfix" >
                <form action="/user/register_handle/" method="post" id="reg_form">
                    {% csrf_token %}
                    <ul>
                        <li>
                            <label>用户名:</label>
                            <input type="text" name="user_name" id="user_name">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>密码:</label>
                            <input type="password" name="pwd" id="pwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>确认密码:</label>
                            <input type="password" name="cpwd" id="cpwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>邮箱:</label>
                            <input type="text" name="email" id="email">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li class="agreement">
                            <input type="checkbox" name="allow" id="allow" checked="checked">
                            <label>同意”天天生鲜用户使用协议“</label>
                            <span class="error_tip2">提示信息</span>
                        </li>
                        <li class="reg_sub">
                            <input type="submit" value="注 册">
                        </li>
                    </ul>
                </form>
            </div>

        </div>
    </div>
{% endblock body %}

templates/df_user/user_center_info.html
{% extends 'df_user/base.html' %}
{% load static %}
{% block body %}

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="/user/info/" class="active">· 个人信息</a></li>
                <li><a href="/user/order/">· 全部订单</a></li>
                <li><a href="/user/site/">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <div class="info_con clearfix">
                <h3 class="common_title2">基本信息</h3>
                <ul class="user_info_list">
                    <li><span>用户名：</span>{{ user_name }}</li>
                    <li><span>联系邮箱：</span>{{ user_email }}</li>
                </ul>
            </div>

            <h3 class="common_title2">最近浏览</h3>
            <div class="has_view_list">
                <ul class="goods_type_list clearfix">
                    {% for g in goods_list %}
                        <li>
                            <a href="/detail/{{ g.id }}/"><img src="/upload/{{ g.gpic }}"></a>
                            <h4><a href="/detail/{{ g.id }}/">{{ g.gtitle }}</a></h4>
                            <div class="operate">
                                <span class="prize">￥{{ g.gprice }}</span>
                                <span class="unit">{{ g.gprice }}/{{ g.unit }}g</span>
                                <a href="#" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock body %}

templates/df_user/user_center_order.html
{% extends 'df_user/base.html' %}

{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/1" class="active">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for orderinfo in page %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ orderinfo.odate|date }}</li>
					<li class="col02">订单号：{{ orderinfo.oid }}</li>
					<li class="col02 stress">已支付</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for order_detail in orderinfo.orderdetailinfo_set.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/upload/{{ order_detail.goods.gpic }}"></li>
                                    <li class="col02">{{ order_detail.goods.gtitle }}<em class="good_price">{{ order_detail.goods.gprice }}</em>元/<em>{{ order_detail.goods.gunit }}</em></li>
									<li class="col03">{{ order_detail.count }}件</li>
									<li class="col04">11.80元</li>	
								</ul>
                                {% endfor %}
							</td>
							<td width="15%">{{ orderinfo.ototal }}元</td>
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
						</tr>
					</tbody>
				</table>
			    {% endfor %}

{#				<ul class="order_list_th w978 clearfix">#}
{#					<li class="col01">2016-8-21 17:36:24</li>#}
{#					<li class="col02">订单号：56872934</li>#}
{#					<li class="col02 stress">已支付</li>			#}
{#				</ul>#}
{#				<table class="order_list_table w980">#}
{#					<tbody>#}
{#						<tr>#}
{#							<td width="55%">#}
{#								<ul class="order_goods_list clearfix">					#}
{#									<li class="col01"><img src="/static/images/goods02.jpg"></li>#}
{#									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	#}
{#									<li class="col03">1</li>#}
{#									<li class="col04">11.80元</li>	#}
{#								</ul>#}
{#								<ul class="order_goods_list clearfix">					#}
{#									<li class="col01"><img src="/static/images/goods02.jpg"></li>#}
{#									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	#}
{#									<li class="col03">1</li>#}
{#									<li class="col04">11.80元</li>	#}
{#								</ul>#}
{#							</td>#}
{#							<td width="15%">33.60元</td>#}
{#							<td width="15%">已付款</td>#}
{#							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>#}
{#						</tr>#}
{#					</tbody>#}
{#				</table>#}

				<div class="pagenation">
                    {% if page.has_previous %}
					    <a href="/user/order/{{ page.previous_page_number }}">上一页</a>
                    {% endif %}

                    {% for index in paginator.page_range %}
                        {% if index == page.number %}
                            <a href="/user/order/{{ index }}" class="active">{{ index }}</a>
                        {% else %}
                            <a href="/user/order/{{ index }}">{{ index }}</a>
                        {% endif %}
                    {% endfor %}

                    {% if page.has_next %}
					    <a href="/user/order/{{ page.next_page_number }}">下一页></a>
                    {% endif %}
				</div>
		</div>
	</div>

    <script type="text/javascript">
    $(function () {
        $('.col04').each(function () {
            count = $(this).prev().text();
            price = $(this).prev().prev().find('.good_price').text();
            $(this).html((parseFloat(count,2)*parseFloat(price,2)).toFixed(2)+'元');
            }

        )
        }

    )
    </script>

{% endblock body %}

templates/df_user/user_center_site.html
{% extends 'df_user/base.html' %}
{% load static %}
{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user.uaddress }}</dd>
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/site/" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushou" value="{{ user.ushou }}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uaddress">{{ user.uaddress }}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="uyoubian" value="{{ user.uyoubian }}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uphone" value="{{ user.uphone }}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock body %}